### ISSUE TITLE
Purpose

### ISSUE THREAD

**Issue by Masynchin** [f-f/spaghetto#1]
The README says that spaghetto is:

> The next iteration of [Spago](https://github.com/purescript/spago).

But why spago needs the next iteration? What is the reason to create this tool? It would be nice if README would have answers for this questions.

**Comment by f-f** [comment]
Hi! The main reason for the rewrite is because the current Spago codebase got quite tangly over time, and since we need to support the [upcoming Registry](https://github.com/purescript/registry-dev) (see there for more info), the effort for the integration was too large and we opted for a rewrite instead, which is going much better.

This is not supposed to be used in production (or at all) just yet, so the readme will stay empty until we are sure this is the right way forward.

That is, I'm actively discouraging you and everyone else reading this from using this tool at all right now.
